#include <cstddef>
#include <cstring>

struct Nickname
{
    Nickname(const char* input)
    {
        if (input) {
            std::size_t n = std::strlen(input) + 1;
            nick_ = new char[n];
            std::memcpy(nick_, input, n);
        }
    }

    ~Nickname() { if (nick_) delete[] nick_; }

private:
    char* nick_ = nullptr;
};

int main()
{
    Nickname n1("Whatever");
    // copy constructor implicitly generated by compiler
    Nickname n2(n1);
    // same for copy assignment operator
    Nickname n3 = n2;
} // n3, n2, n1 go out-of-scope; destructors called;
  // double free and crash
