
PRG            = morse
OBJ            = ${PRG}.o
PROGRAMMER     = arduino
PORT           = /dev/ttyUSB0
MCU_TARGET     = atmega328p 
AVRDUDE_TARGET = atmega328p
OPTIMIZE       = -O3
DEFS           =
LIBS           =
BAUDRATE       = 115200

HZ          = 16000000

# You should not have to change anything below here.

CC             = avr-gcc

# Override is only needed by avr-lib build system.

override CFLAGS        = -g -std=c99 -DF_CPU=$(HZ) -Wall $(OPTIMIZE) -mmcu=$(MCU_TARGET) $(DEFS)
override LDFLAGS       = -Wl,-Map,$(PRG).map

OBJCOPY        = avr-objcopy
OBJDUMP        = avr-objdump
SIZE           = avr-size
AVRDUDE        = avrdude
SCREEN         = screen
MINITERM       = pyserial-miniterm

BOOT_PAD       = .bootloader-pad

all: $(PRG).elf lst text

$(PRG).elf: $(OBJ)
	$(CC) $(CFLAGS) $(LDFLAGS) -o $@ $^ $(LIBS)

clean:
	rm -rf *.o $(PRG).elf *.eps *.png *.pdf *.bak *.hex *.bin *.srec
	rm -rf *.lst *.map $(BOOT_PAD) $(EXTRA_CLEAN_FILES)

lst:  $(PRG).lst

%.lst: %.elf
	$(OBJDUMP) -h -S $< > $@

# Rules for building the .text rom images

text: hex bin srec

hex:  $(PRG).hex
bin:  $(PRG).bin
srec: $(PRG).srec

%.hex: %.elf $(BOOT_PAD)
	$(OBJCOPY) -j .text -j .data -O ihex $< $@
	$(OBJCOPY) --add-section .bootloader=$(BOOT_PAD) $< .padded-$<
	$(SIZE) --mcu=${MCU_TARGET} --format=avr .padded-$<

%.srec: %.elf
	$(OBJCOPY) -j .text -j .data -O srec $< $@

%.bin: %.elf
	$(OBJCOPY) -j .text -j .data -O binary $< $@

install:  $(PRG).hex
	$(AVRDUDE) -p $(AVRDUDE_TARGET) -c $(PROGRAMMER) -P $(PORT) \
        -b $(BAUDRATE) -v -U flash:w:$(PRG).hex 

screen:
	$(SCREEN) $(PORT)

miniterm:
	$(MINITERM) $(PORT)

$(BOOT_PAD):
	dd if=/dev/zero of=$(BOOT_PAD) bs=512 count=1


