#lang plait

(define char-map
  (hash (list
    (pair #\space " ")
    (pair #\. ".")
    (pair #\1 ".____")
    (pair #\2 "..___")
    (pair #\3 "...__")
    (pair #\4 "...._")
    (pair #\5 ".....")
    (pair #\6 "_....")
    (pair #\7 "__...")
    (pair #\8 "___..")
    (pair #\9 "____.")
    (pair #\0 "_____")
    (pair #\a "._")
    (pair #\A "._")
    (pair #\b "_...")
    (pair #\B "_...")
    (pair #\c "_ . _ .")
    (pair #\C "_ . _ .")
    (pair #\d "_ . .")
    (pair #\D "_ . .")
    (pair #\e ".")
    (pair #\E ".")
    (pair #\f ".._.")
    (pair #\F ".._.")
    (pair #\g "__.")
    (pair #\G "__.")
    (pair #\h "....")
    (pair #\H "....")
    (pair #\i "..")
    (pair #\I "..")
    (pair #\j ".___")
    (pair #\J ".___")
    (pair #\k "_._")
    (pair #\K "_._")
    (pair #\l "._..")
    (pair #\L "._..")
    (pair #\m "__")
    (pair #\M "__")
    (pair #\n "_.")
    (pair #\N "_.")
    (pair #\o "___")
    (pair #\O "___")
    (pair #\p ".__.")
    (pair #\P ".__.")
    (pair #\q "___")
    (pair #\Q "___")
    (pair #\r "._.")
    (pair #\R "._.")
    (pair #\s "...")
    (pair #\S "...")
    (pair #\t "_")
    (pair #\T "_")
    (pair #\u ".._")
    (pair #\U ".._")
    (pair #\v "..._")
    (pair #\V "..._")
    (pair #\w ".__")
    (pair #\W ".__")
    (pair #\x "_.._")
    (pair #\X "_.._")
    (pair #\y "_.__")
    (pair #\Y "_.__")
    (pair #\z "__..")
    (pair #\Z "__.."))))

(define (morse-code-r s f space)
  (cond 
    [(empty? s) ""]
    [(and space (char=? #\space (first s))) (morse-code-r (rest s) #f #t)]
    [(char=? #\space (first s)) (string-append (some-v (hash-ref char-map (first s))) (morse-code-r (rest s) #f #t))]
    [f (string-append (some-v (hash-ref char-map (first s))) (morse-code-r (rest s) #f #f))]
    [(not f) (string-append (string-append " " (some-v (hash-ref char-map (first s)))) (morse-code-r (rest s) #f #f))]))

(define (morse-code s)
  (morse-code-r (string->list s) #t #f))